apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/external-secrets
  - ../../base/cert-manager
  - ../../base/monitoring
  - ../../namespaces
  - ../../rbac
  - ../../network-policies
  - ../../policies/gatekeeper
  - ../../policies/kyverno

commonLabels:
  environment: dev
  managed-by: kustomize

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
