apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
  labels:
    {{- include "jol-frontend.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "jol-frontend.selectorLabels" . | nindent 6 }}
